---
title: "Penguins"
author: "Mia Fitzgerald"
date: "4/21/2026"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
library(knitr)
library(tidyverse)
library(readxl)
library(DBI)
library(dbplyr)
library(duckdb)

```


### Loading Three Worksheets


```{r}
penguins_t_xl <- read_excel("penguins.xlsx", sheet = "Torgersen Island", na = "NA")
penguins_b_xl <- read_excel("penguins.xlsx", sheet = "Biscoe Island", na = "NA")
penguins_d_xl <- read_excel("penguins.xlsx", sheet = "Dream Island", na = "NA")

```


^[Question 1 complete]


### Stacking the Three Worksheets


```{r}
combined_penguins <- bind_rows(penguins_b_xl, penguins_d_xl, penguins_t_xl)

combined_penguins %>%
  kable()

```


^[Question 2 complete]


### Bill Depth Versus Bill Length by Island


```{r}
combined_penguins %>%
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point() + 
  facet_wrap(~island)

```


^[Question 3 complete]


### Average Body Masses for the Different Penguin Species


```{r}
combined_penguins %>%
  select(species, body_mass_g) %>%
  group_by(species) %>%
  summarize(avg_body_mass = mean(body_mass_g, na.rm = TRUE)) %>%
  kable() 

```


^[Question 4 complete]


### Started a New, Temporary DuckDB Database


```{r}
con <- DBI::dbConnect(duckdb::duckdb())

dbWriteTable(con, "diamonds", ggplot2::diamonds)

sql <- "
  SELECT carat, cut, clarity, color, price 
  FROM diamonds 
  WHERE price > 18800
"
as_tibble(dbGetQuery(con, sql))


```


^[Question 5 complete]

